timezone_id = "Europe/London"
tech_support_person = "Elementary issue, dear watson"

[brand]
instance_name = "Knot"
domain = "localhost:8080"

[niche]
date_time_format = "%a %d/%m/%y @ %H:%M"
tech_support = "https://github.com/BurntNail/knot/issues/new?assignees=&labels=&projects=&template=bug_report.md"


[mail]
username = "knot@mail.maguire.tech"
password = "Q8p3%D85R6**jR"
smtp = "smtppro.zoho.eu"
#username = "kingsley@arapaima.info"
#password = "wSsVR61w+0KjCvh0mTSvIL04m10AVFmkHUspi1OguiStT/6QosdplUfIUwDxGqJKFGY4R2FEo7x7mxlV0GIM3IgsygwGDyiF9mqRe1U4J3x17qnvhDzJX2xdkRKLJY8KxwhqmGZnEM8j+g=="
#smtp = "smtp.zeptomail.com"
username_domain = "maguire.tech"
