# fly.toml app configuration file generated for vent on 2024-11-21T10:20:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vent'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
grace_period = "5s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthcheck"



[[files]]
	guest_path="/config.toml"
	local_path="config.toml"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
