ALTER TABLE people DROP COLUMN IF EXISTS person_name;
ALTER TABLE people ADD COLUMN first_name TEXT NOT NULL;
ALTER TABLE people ADD COLUMN surname TEXT NOT NULL;
ALTER TABLE people ADD COLUMN form TEXT NOT NULL;